### ISSUE TITLE
IsNumberString returns false for none integers

### ISSUE THREAD

**Issue by AmirSasson** [19majkel94/class-transformer-validator#10]
such as "-0.8" a valid numeric string, i get an error.
seems like the regex used to validate that missing a **dot**

**Comment by MichalLytek** [comment]
This is the regex:
https://github.com/chriso/validator.js/blob/master/src/lib/isNumeric.js

If you think it's buggy, create an issue or PR on `validator.js` repository.

**Comment by AmirSasson** [comment]
submitted a [PR](https://github.com/chriso/validator.js/pull/810) to validator JS
