### ISSUE TITLE
Update deps to class-transformer 0.2.0

### ISSUE THREAD

**Issue by quezak** [19majkel94/class-transformer-validator#15]
I recently updated to class-transformer 0.2.0, becuase I wanted to use the `discriminator` feature that they introduced. From my brief tests it looks like it still works with this package, but my use cases are not too complicated, so I can't say everything's ok :) Anyway, it may be worth releasing with updated deps, probably as v0.7 since it's theoretically a breaking change for class-transformer.

**Comment by MichalLytek** [comment]
@quezak 
Feel free to make a PR for that 😉

**Comment by quezak** [comment]
@19majkel94 there you go :)
