### ISSUE TITLE
class-transformer 0.2.2 breaks transformAndValidate

### ISSUE THREAD

**Issue by eyexpo-isaac** [19majkel94/class-transformer-validator#20]
It should relate to [this issue](https://github.com/typestack/class-transformer/issues/255#issuecomment-491013860) in class-transformer after they released [0.2.2](https://github.com/typestack/class-transformer/releases/tag/v0.2.2) yesterday 

```typescript
import { transformAndValidate } from 'class-transformer-validator';

class User {
  @IsEmail()
  identifier!: string;

  @IsString()
  password!: string;
}

const user: User = {
  identifier: 'johndoe@gmail.com',
  password: 'password123',
};

const userJson: string = JSON.stringify(user);

await transformAndValidate(User, userJson)
  .then(async (): Promise<void> => Promise.resolve())
  .catch(async (err: Error): Promise<never> => Promise.reject(err));
```

Throw error 
`TypeError: Reflect.getMetadata is not a function`

Which was working fine before(before they upgrade to 0.2.2)

By adding 
```typescript
import 'reflect-metadata';
```
at the top solved this issue.

**Comment by NoNameProvided** [comment]
This is probably an upstream issue in class-transformer, I have commented on your issue at typestack/class-transformer#255, please continue the conversation there.

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒
