### ISSUE TITLE
Typing for `transformAndValidate` with array is not correct

### ISSUE THREAD

**Issue by coler-j** [19majkel94/class-transformer-validator#27]
The types for `transformAndValidate` is declared as:
`export declare function transformAndValidate<T extends object>(classType: ClassType<T>, object: object, options?: TransformValidationOptions): Promise<T>;`

Where the return is typed as `<T>`

However, if the return of `transformAndValidate` is an array of transformed instances then you need t do something like this to get the typing correct:

`as unknown as InstanceClass[]`

**Comment by MichalLytek** [comment]
`transformAndValidate` has overloads and has a one for array:

https://github.com/MichalLytek/class-transformer-validator/blob/5d25d52e473f0280a3e7a354e0e141416f771ebb/src/index.ts#L39-L43

Which is working correctly:

![image](https://user-images.githubusercontent.com/10618781/86536788-a64e5e80-beea-11ea-94d4-8bf4bf7d8de9.png)
