### ISSUE TITLE
Simple custom validators

### ISSUE THREAD

**Issue by ghost** [19majkel94/class-transformer-validator#33]
I don't understand why creating custom validators need require so much boilerplate with class creation etc. Surely there should be a simple way to create custom validators that take messages? E.g.

    @IsString
    @IsNotEmpty
    @ValidIf(o.section === "SomeSectionName", { message: "Wrong section" })
    myProperty!: string

Am I missing a simple way of doing this without creating a constraint class and then registering a decorator or using the `@Validate(MyConstraint, { message: "Wrong section" })` form?

**Comment by MichalLytek** [comment]
Please ask on `class-validator` GitHub repository 😉
