### ISSUE TITLE
Synchronous validation

### ISSUE THREAD

**Issue by nicolaslt** [19majkel94/class-transformer-validator#4]
Would it be possible to add wrapping of  [synchronous validation](https://www.npmjs.com/package/class-validator#synchronous-validation) ?

**Comment by MichalLytek** [comment]
Of course. I prefer do all the thing async in node.js so I've created only async method. Do you think that I should create new function `transformAndValidateSync` or just implement it as an option `{ sync: true }` to the already existing `transformAndValidate` function?

**Comment by nicolaslt** [comment]
My personal preference would be a new, it makes the return type clearer.

**Comment by MichalLytek** [comment]
Typescript allows for changing return type of overloaded function, so when `{ sync: true }` option is passed, the returned type is `T`, not `Promise<T>`. It is used to return `Promise<T[]>` when array is passed as parameter.

But as the internals needs to be changes, it's better to create new function than overloading the overloaded method.

**Comment by nicolaslt** [comment]
Just noticed you implemented it already. :+1: 
Any indicative release date?

**Comment by MichalLytek** [comment]
Yes, it's not a breaking change so I will release it today in 0.3.1 😉 0.4.0 has to wait for transform/validate json array.

**Comment by nicolaslt** [comment]
:+1:

**Comment by MichalLytek** [comment]
Released in v0.4.0! 🎉
