### ISSUE TITLE
could i remove unknow properties

### ISSUE THREAD

**Issue by yoohan-dex** [19majkel94/class-transformer-validator#9]
like yup noUnknown. not only validate the object but also remove properties I didn't define.

**Comment by MichalLytek** [comment]
https://github.com/typestack/class-validator#whitelisting

**Comment by yoohan-dex** [comment]
@19majkel94 sorry... I meant that after validated and transformed the object, the function will return a new object that without properties I didn't define in type.

**Comment by MichalLytek** [comment]
This lib is only a wrapper on `class-validator`, so please go to it's repo and create a proposal for this behavior 😉

**Comment by yoohan-dex** [comment]
Ok thank you 😄

From yoohoo

On 26 Feb 2018, 03:57 +0800, Michał Lytek <notifications@github.com>, wrote:

This lib is only a wrapper on class-validator, so please go to it's repo and create a proposal for this behavior 😉
